/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20PokeTokenSol from "./ERC20-PokeToken.sol";
export type { erc20PokeTokenSol };
export type { Lottery } from "./Lottery";
export type { LotteryToken } from "./LotteryToken";
export type { PokNFT } from "./PokNFT";
