/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Lottery } from "./Lottery";
export type { LotteryToken } from "./LotteryToken";
export type { PokeNFT } from "./PokeNFT";
export type { PokeToken } from "./PokeToken";
export type { Shop } from "./Shop";
