/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPokeNFT__factory } from "./IPokeNFT__factory";
export { IPokeToken__factory } from "./IPokeToken__factory";
