/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPokeNFT,
  IPokeNFTInterface,
} from "../../../contracts/interfaces/IPokeNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPokeNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IPokeNFTInterface {
    return new Interface(_abi) as IPokeNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPokeNFT {
    return new Contract(address, _abi, runner) as unknown as IPokeNFT;
  }
}
